a = [
    'Dashboard', 'Companies', 'Branches',
    'Users', 'Features', 'Roles',
    'Permission', 'Departments', 'Applications',
    'Chat', 'Calls', 'Voice Call',
    'Video Call', 'Outgoing Call', 'Incoming Call',
    'Call History', 'Calendar', 'Email',
    'To Do', 'Notes', 'Social Feed',
    'File Manager', 'Kanban', 'Invoices',
    'Super Admin', 'Dashboard', 'Companies',
    'Subscriptions', 'Packages', 'Domain',
    'Purchase Transaction', 'Horizontal', 'Detached',
    'Modern', 'Two Column', 'Hovered',
    'Boxed', 'Horizontal Single', 'Horizontal Overlay',
    'Horizontal Box', 'Menu Aside', 'Transparent',
    'Without Header', 'RTL', 'Dark',
    'Clients', 'Projects', 'Projects',
    'Tasks', 'Task Board', 'Contacts',
    'Companies', 'Deals', 'Leads',
    'Pipeline', 'Analytics', 'Activities',
    'Employees', 'Employees List', 'Employees Grid',
    'Employees Details', 'Departments', 'Designations',
    'Policies', 'Tickets', 'Tickets',
    'Tickets Detail', 'Holidays', 'Attendance',
    'Leaves', 'Leaves (Admin)', 'Leaves (Employee)',
    'Leave Settings', 'Attendance (Admin)', 'Attendance (Employee)',
    'Timesheet', 'Shift & Schedule', 'Overtime',
    'Performance', 'Performance Indicator', 'Performance Review',
    'Performance Appraisal', 'Goal List', 'Goal Type',
    'Tickets Detail', 'Holidays', 'Attendance',
    'Leaves', 'Leaves (Admin)', 'Leaves (Employee)',
    'Leave Settings', 'Attendance (Admin)', 'Attendance (Employee)',
    'Timesheet', 'Shift & Schedule', 'Overtime',
    'Performance', 'Performance Indicator', 'Performance Review',
    'Performance Appraisal', 'Goal List', 'Goal Type',
    'Training', 'Training List', 'Trainers',
    'Leaves', 'Leaves (Admin)', 'Leaves (Employee)',
    'Leave Settings', 'Attendance (Admin)', 'Attendance (Employee)',
    'Timesheet', 'Shift & Schedule', 'Overtime',
    'Performance', 'Performance Indicator', 'Performance Review',
    'Performance Appraisal', 'Goal List', 'Goal Type',
    'Training', 'Training List', 'Trainers',
    'Leave Settings', 'Attendance (Admin)', 'Attendance (Employee)',
    'Timesheet', 'Shift & Schedule', 'Overtime',
    'Performance', 'Performance Indicator', 'Performance Review',
    'Performance Appraisal', 'Goal List', 'Goal Type',
    'Training', 'Training List', 'Trainers',
    'Timesheet', 'Shift & Schedule', 'Overtime',
    'Performance', 'Performance Indicator', 'Performance Review',
    'Performance Appraisal', 'Goal List', 'Goal Type',
    'Training', 'Training List', 'Trainers',
    'Performance', 'Performance Indicator', 'Performance Review',
    'Performance Appraisal', 'Goal List', 'Goal Type',
    'Training', 'Training List', 'Trainers',
    'Performance Appraisal', 'Goal List', 'Goal Type',
    'Training', 'Training List', 'Trainers',
    'Training Type', 'Promotion', 'Resignation',
    'Termination', 'Jobs', 'Candidates',
    'Training', 'Training List', 'Trainers',
    'Training Type', 'Promotion', 'Resignation',
    'Termination', 'Jobs', 'Candidates',
    'Refferals', 'Sales', 'Estimates',
    'Training Type', 'Promotion', 'Resignation',
    'Termination', 'Jobs', 'Candidates',
    'Refferals', 'Sales', 'Estimates',
    'Termination', 'Jobs', 'Candidates',
    'Refferals', 'Sales', 'Estimates',
    'Invoices', 'Payments', 'Expenses',
    'Refferals', 'Sales', 'Estimates',
    'Invoices', 'Payments', 'Expenses',
    'Invoices', 'Payments', 'Expenses',
    'Provident Fund', 'Taxes', 'Accounting', 'Categories', 'Budgets', 'Budget Expenses', 'Budget Revenues', 'Payroll', 'Employee Salary', 'Payslip', 'Payroll Items']

console.log(a.length);
